# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cc1H9pSt5GW50YrQ5Lxidz_CsPQIBeer
"""

pip install pycryptodome rsa

import rsa
from Crypto.Cipher import AES
from Crypto.Random import get_random_bytes

# Generate RSA keys
public_key, private_key = rsa.newkeys(512)

# AES Key
aes_key = get_random_bytes(16)

# Message
message = "My laptop password is 1234Cryptography"

# Create Signature
signature = rsa.sign(
    message.encode(),
    private_key,
    'SHA-256'
)

# AES Encryption
cipher = AES.new(
    aes_key,
    AES.MODE_EAX
)

ciphertext, tag = cipher.encrypt_and_digest(
    message.encode()
)

print("Encrypted Message:")
print(ciphertext)

# AES Decryption
cipher2 = AES.new(
    aes_key,
    AES.MODE_EAX,
    nonce=cipher.nonce
)

plaintext = cipher2.decrypt(ciphertext)

print("\nDecrypted Message:")
print(plaintext.decode())

# Signature Verification
try:
    rsa.verify(
        plaintext,
        signature,
        public_key
    )

    print("Signature Verified and its valid")

except:
    print("Invalid Signature")